# Generated by Django 5.1.2 on 2025-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='annual_income',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='hobby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='User_Images/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.BigIntegerField(blank=True, default=1010101010, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, choices=[('worker', 'Worker'), ('student', 'Student'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
