# Generated by Django 5.1.2 on 2025-02-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0003_alter_register_about_alter_register_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='referral_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
