# Generated by Django 5.1.2 on 2025-02-22 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0005_register_created_at_register_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only letters and numbers are allowed.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
