# Generated by Django 5.1.2 on 2025-02-22 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0006_alter_register_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='First name can contain letters, numbers, and special characters.', regex='^[\\w\\W]+$')]),
        ),
    ]
