# Generated by Django 5.1.2 on 2025-06-20 11:47

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0008_task_task_url_alter_bankdetails_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskuserassignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='users_assigned',
            field=models.ManyToManyField(related_name='assigned_tasks', through='nass.TaskUserAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskuserassignment',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='taskuserassignment',
            unique_together={('task', 'user')},
        ),
    ]
