# Generated by Django 5.1.2 on 2025-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0009_alter_taskuserassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskuserassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskuserassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
