# Generated by Django 5.1.2 on 2025-08-20 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nass', '0010_alter_taskuserassignment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskuserassignment',
            old_name='is_claimed',
            new_name='commission_distributed',
        ),
        migrations.RemoveField(
            model_name='taskuserassignment',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='taskuserassignment',
            name='proof_screenshot',
        ),
        migrations.AddField(
            model_name='task',
            name='total_commission_pool',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total commission pool for this task (auto-calculated)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='commission_distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='commission_distribution_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskuserassignment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='task_screenshots/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskuserassignment',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskuserassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='nass.task'),
        ),
        migrations.AlterField(
            model_name='taskuserassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
